#!/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

exec >>bpftools-start-stderrout.txt
exec 2>&1

echo "args: $@"
echo "hostname: $(hostname)"

if [ -e bpftools-pids.txt ]; then
    while read -r pid; do
        kill -s SIGINT "$pid"
    done < bpftools-pids.txt

    # Wait for bpftrace processes to flush output and exit
    while read -r pid; do
        while kill -0 "$pid" 2>/dev/null; do
            sleep 0.1
        done
    done < bpftools-pids.txt

    find . -name "*.txt" | while read -r f; do
        echo "Compressing: $f"
        xz -3 -T 0 "$f"
    done
else
    echo "Could not find bpftools-pids.txt"
    echo "PWD: $(pwd)"
    echo "LS:"
    /bin/ls -l
    exit 1
fi
